### PR TITLE
add a53 optimization flags for cores

### PR DESCRIPTION
**Pull request by loki666**
add GCC optimizations flags for RG35XX+/H cores

### CODE REVIEW

**Comment by sinedied** [comment]
@loki666 why removing this one, did you encounter an issue? This looked like a great optimization!

**Comment by loki666** [comment]
Don't remember...
PR is still there and seems to still merge cleanly, so up for the taking.

**Comment by sinedied** [comment]
@loki666 I don't think it's mergeable anymore as it seems you deleted the repo from where the PR is coming from :(

**Comment by loki666** [comment]
Arf right...
Well one can still recreate it with the content of the PR...
But I think I closed it because it didn't yield any significant performance improvement...
Anyway I moved from MinUI to ROCKNIX

**Pull request closed without merging**
