### PR TITLE
Visually better brigthness steps for A30 / my282

### PR DESCRIPTION
**Pull request by weakset**
Using the full range, tested visually with real hardware.

### CODE REVIEW

**Comment by shauninman** [comment]
There must be a difference in panels because on my device there's no noticeable change in the range between 32 and 255.

**Comment by shauninman** [comment]
On my hardware the jump from 5-7 is much larger than the step from 4-5 and 12-50 is huge. 50-70 is imperceptible. 70-120 is barely noticeable. 120-180 and 180-255 are imperceptible.

**Comment by shauninman** [comment]
But since I rarely use the top two thirds of the brightness ramp I'm going to go ahead and open it up a little to account for panel variance.

**Comment by weakset** [comment]
My device also had few deadzones, but I did expect them to be the same for everyone. Even with stock OS, brightness 2/10 and 3/10 are the same.

**Pull request closed without merging**
